/*
  Nome: clientes.sql
  Fun˛“o: criar e atualizar os objetos dentro do banco de dados "lazdemos_gsl.fdb".
          Foco na cria˛“o e atualiza˛“o da tabela "CLIENTES".
  Observa˛“o: Ao executar usando:
        >isql -ch iso8859_1 -i <script.sql>
        retorna uma mensagem dizendo:
        "Rolling back work."
        Apesar disso, todo funcionou direitinho.
  Data: 20/02/2024
  Autor: Hamacker <sirhamacker [em] gmail.com>
*/
/*
Function: create and update objects within the "lazdemos_gsl.fdb" database.
           Focus on creating and updating the "CLIENTES" table.
   Note: When running using:
         >isql -ch iso8859_1 -i <script.sql>
         returns a message saying:
         "Rolling back work."
         Despite this, everything worked fine. Maybe this message is a bug.
*/
set sql dialect 3;
set clientlib 'fbclient.dll';
connect 'C:\Projetos-fpc\lazdemos_gsl\db\LAZDEMOS_GSL.FDB';
set autoddl on;
set names iso8859_1;
set transaction
  read write
  isolation level read committed
  wait
  lock timeout 180;

set bail on;
set list on;
--shell echo ***** INICIO *****

CREATE or alter EXCEPTION ERR 'Erro generico, favor verificar COM ATEN«√O';
GRANT USAGE ON EXCEPTION ERR TO PUBLIC;

SET TERM ^;
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(SELECT * from  RDB$RELATIONS WHERE RDB$RELATION_NAME='CLIENTES' )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
      CREATE TABLE CLIENTES (
        ID_CLIENTE BIGINT generated by default as identity not null,
        NOME_COMPLETO CHAR(120),
        STATUS CHAR(1) DEFAULT ''A'') ;
      ';
  END
END
^

COMMIT;^

-- Comentar a tabela
COMMENT ON TABLE CLIENTES IS 'Rela˛“o de clientes';^
COMMENT ON COLUMN CLIENTES.ID_CLIENTE IS 'Codigo do cliente';^
COMMENT ON COLUMN CLIENTES.NOME_COMPLETO IS 'Nome do cliente';^
COMMENT ON COLUMN CLIENTES.STATUS IS 'Situa˛“o do cliente(A=Ativo, C=Cancelado)';^

-- Permiss“o a tabela
grant select on clientes to PUBLIC; ^
grant select, delete, insert, update on clientes to SYSDBA; ^

COMMIT;^

-- Apagando chave prinmaria antiga
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_constraints
       where rdb$constraint_name='PK2_CLIENTES' )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
      ALTER TABLE CLIENTES DROP CONSTRAINT PK2_CLIENTES;
      ';
  END
END
^

COMMIT;^

-- Chave prinmaria
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_constraints
       where rdb$constraint_name='PK_CLIENTES' )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
      ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE);
      ';
  END
END
^

COMMIT;^

-- Constraint status apenas A ou C
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_constraints
       where rdb$constraint_name='CHK_CLIENTES_STATUS' )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
      ALTER TABLE CLIENTES
        DROP CONSTRAINT CHK_CLIENTES_STATUS
      ';
  END
END
^

COMMIT;^


-- Constraint status apenas A ou C
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_constraints
       where rdb$constraint_name='CHK_CLIENTES_STATUS'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
        ADD CONSTRAINT CHK_CLIENTES_STATUS
        CHECK (
        STATUS IN (''A'',''C'',''P'')
        );
      ';
  END
END
^

COMMIT;^

-- Adicionando campo CNPJ
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='CNPJ'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
        ADD CNPJ CHAR(14)
      ';
  END
END
^

COMMIT;^

-- CNPJ n“o pode ter nulos
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='CNPJ'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
       UPDATE CLIENTES SET CNPJ='''' WHERE CNPJ IS NULL;
      ';
  END
END
^

COMMIT;^

-- CNPJ n“o pode ter nulos not nulll
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='CNPJ'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
      ALTER TABLE CLIENTES ALTER CNPJ SET NOT NULL
      ';
  END
END
^

COMMIT;^

-- Adicionando campo LAST_UPDATE
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='LAST_UPDATE'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
        ADD LAST_UPDATE timestamp
        DEFAULT current_timestamp;
      ';
  END
END
^

COMMIT;^

-- Adicionando campo LAST_UPDATE
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='LAST_OWNER'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
          ADD LAST_OWNER varchar(60)
          DEFAULT current_user;
      ';
  END
END
^

COMMIT;^

-- Inserindo dados para testes
--
/*
insert into clientes (nome_completo, cnpj, status)
values ('BANCO DO BRASIL SA 00000000000191', '', 'A');^

insert into clientes (nome_completo, cnpj, status)
values ('BANCO DO BRASIL S A MANAUS 00000000000272', '', 'A');^

insert into clientes (nome_completo, cnpj, status)
values ('presidente vargas belem (pa) 00000000000353', '', 'A');^

insert into clientes (nome_completo, cnpj, status)
values ('BANCO DO BRASIL S A SANTOS 00000000000434', '', 'A');^

insert into clientes (nome_completo, cnpj, status)
values ('Banco do Brasil SA Campos Dos Goytacazes (RJ), 00000000000515', '', 'A');^
*/

-- Video  #11
-- Criando campo STATUS_COM (compute by) - FANTASIA
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='STATUS_COM'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
          ADD STATUS_COM COMPUTED BY ((CAST(''*'' AS VARCHAR(15))))
      ';
  END
END
^

COMMIT;^

-- Criando campo STATUS_COM (compute by) - REAL
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='STATUS_COM'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
          ALTER STATUS_COM COMPUTED BY (
                  CAST(
                    CASE
                      WHEN STATUS=''A'' THEN ''Ativo''
                      WHEN STATUS=''C'' THEN ''Cancelado''
                      WHEN STATUS=''P'' THEN ''P”ralisado''
                      ELSE ''Indefinido''
                    END AS VARCHAR(15)
                  )
                )
      ';
  END
END

^

COMMIT;^

-- Criando campo STATUS_COM (compute by)  - FANTASIA
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='MODIFICADO_COM'
       )) then
    existe=true;
  if (not existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES
          ADD MODIFICADO_COM COMPUTED BY ((CAST(''*'' AS VARCHAR(40))))
      ';
  END
END
^

COMMIT;^

-- Criando campo STATUS_COM (compute by)  - REAL
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='MODIFICADO_COM'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    execute statement
      '
        ALTER TABLE CLIENTES ALTER MODIFICADO_COM COMPUTED BY (
                  CAST(
                    CASE
                      WHEN (last_update<=''01.01.1970'') THEN ''Inalterado''
                      WHEN (coalesce(last_owner,'''')='''') then left(cast(last_update as varchar(24))||'' anonimo'', 40)
                      ELSE left(cast(last_update as varchar(24))||'' ''||last_owner, 40)
                    END AS VARCHAR(40)
                  )
                )
      ';
  END
END
^

COMMIT;^

-- Ajustando campos do tipo identity
-- ALTER TABLE CLIENTES ALTER COLUMN ID_CLIENTE RESTART WITH 6
-- 
execute block as
declare variable existe boolean;
declare variable prox_id int;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='ID_CLIENTE'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    select max(id_cliente)+1 from clientes
    into :prox_id;
    if (prox_id is null) then
      prox_id=1;

    execute statement
      '
      ALTER TABLE
        CLIENTES ALTER COLUMN ID_CLIENTE
        RESTART WITH '||cast(:prox_id as varchar(8))||'
      ';
  END
END
^
COMMIT;^

--
-- Criando um indice comum para o campo nome_completo
--
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='NOME_COMPLETO'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    existe=false;
    if (exists(
      select * from rdb$indices
      where rdb$index_name = 'IDX_CLIENTES_NOME_COMPLETO'
      )) then existe=true;
    if (not existe) then
    begin
      execute statement
        '
        CREATE INDEX IDX_CLIENTES_NOME_COMPLETO
        ON CLIENTES (NOME_COMPLETO)
        ';
    end
  END
END
^
COMMIT;^

-- Criando um indice unico para CNPJ, deve verificar:
--   existencia do campo CNPJ
--   n„o existir CNPJ duplicado
--   e ent„o criar o indice unico
execute block as
declare variable existe boolean;
begin
  existe=false;
  if (EXISTS(
       select * from rdb$relation_fields rf
       where rf.rdb$relation_name='CLIENTES' and rdb$field_name='CNPJ'
       )) then
    existe=true;
  if (existe) then
  BEGIN
    existe=false;
    if (exists(
      select * from clientes c
      where
        ((
        select count(*) from clientes c2
        where c2.cnpj=c.cnpj
        )>1)
      )) then existe=true;
   if (not existe) then
   begin
      if (exists(
        select * from rdb$relation_constraints
        where rdb$constraint_name = 'UNQ_CLIENTES_CNPJ'
        )) then existe=true;
      if (not existe) then
      begin
        execute statement
          '
          ALTER TABLE CLIENTES
            ADD CONSTRAINT UNQ_CLIENTES_CNPJ
            UNIQUE (CNPJ);
          ';
      end
    end
  END
END
^
COMMIT;^

--shell echo ***** FIM *****

-- fim do script
--quit; ^
SET TERM ; ^
